context:
  name: preferences-rs-rust-source
  version: "2.0.0"
  sha256: "8aa13f1c206db011ed01612acd46246d4d77fc3d9dd6f42f7ba7cbf762441df8"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/andybarron/preferences-rs/archive/refs/tags/v${{ version }}.tar.gz
  sha256: ${{ sha256 }}

build:
  number: 0
  script:
    env:
      PKG_SHA256: ${{ sha256 }}
    content:
      - if: linux or osx
        then: "${RECIPE_DIR}/install-rust-source.sh"
        else: "%RECIPE_DIR%\\install_rust_source.bat"

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - setuptools-rust

tests:
  - script:
      - if: linux or osx
        then:
          - test -f $PREFIX/src/rust-libraries/${{ name }}-${{ version }}/LICENSE.txt
        else:
          - if ! exist %PREFIX%\\src\\rust-libraries\\${{ name }}-${{ version }}\\LICENSE.txt exit 1
  # - downstream: serial-monitor-rust

about:
  homepage: https://github.com/andybarron/preferences-rs
  summary: 'Read and write user-specific application data in (stable!) Rust.'
  description: |
    Read and write user-specific application data in Rust
  license: MIT
  license_file:
    - LICENSE.txt
    - THIRDPARTY.yml
  documentation: https://docs.rs/preferences
  repository: https://github.com/andybarron/preferences-rs

extra:
  recipe-maintainers:
    - MementoRC
