context:
  version: "1.0.1"

package:
  name: guetzli
  version: ${{ version }}

source:
  - url: https://github.com/google/guetzli/archive/refs/tags/v${{ version }}.tar.gz
    sha256: e52eb417a5c0fb5a3b08a858c8d10fa797627ada5373e203c196162d6a313697
  - url: https://github.com/google/guetzli/releases/download/v1.0/bees.png
    target_directory: test-image
    sha256: 2c1784bf4efb90c57f00a3ab4898ac8ec4784c60d7a0f70d2ba2c00af910520b

build:
  skip: win
  script:
    - make
    - install -Dm755 bin/Release/guetzli $PREFIX/bin/guetzli

requirements:
  build:
    - ${{ compiler('cxx') }}
    - make
    - pkg-config
    - coreutils
  host:
    - libpng
    - zlib
  ignore_run_exports:
    from_package:
      - zlib

tests:
  - script:
      # compress test image
      - guetzli test-image/bees.png bees.jpg
    files:
      source:
        - test-image/

about:
  homepage: https://github.com/google/guetzli
  license: Apache-2.0
  summary: Perceptual JPEG encoder
