context:
  version: "0.3.6"

package:
  name: cargo-binutils
  version: ${{ version }}

source:
  url: https://github.com/rust-embedded/cargo-binutils/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 431fb12a47fafcb7047d41bdf4a4c9b77bea56856e0ef65c12c40f5fcb15f98f

build:
  script: cargo install --root $PREFIX --no-track --locked --path .

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}

tests:
  - package_contents:
      files:
        - bin/cargo-cov${{ ".exe" if win}}
        - bin/cargo-nm${{ ".exe" if win}}
        - bin/cargo-objcopy${{ ".exe" if win}}
        - bin/cargo-objdump${{ ".exe" if win}}
        - bin/cargo-profdata${{ ".exe" if win}}
        - bin/cargo-readobj${{ ".exe" if win}}
        - bin/cargo-size${{ ".exe" if win}}
        - bin/cargo-strip${{ ".exe" if win}}
        - bin/rust-ar${{ ".exe" if win}}
        - bin/rust-cov${{ ".exe" if win}}
        - bin/rust-ld${{ ".exe" if win}}
        - bin/rust-lld${{ ".exe" if win}}
        - bin/rust-nm${{ ".exe" if win}}
        - bin/rust-objcopy${{ ".exe" if win}}
        - bin/rust-objdump${{ ".exe" if win}}
        - bin/rust-profdata${{ ".exe" if win}}
        - bin/rust-readobj${{ ".exe" if win}}
        - bin/rust-size${{ ".exe" if win}}
        - bin/rust-strip${{ ".exe" if win}}
  - script:
      - if: unix
        then:
          - cd demo-crate
          - cargo size --release | grep -q "text\|__TEXT"
          - cargo nm --release | grep -q "main"
        else:
          - cd demo-crate
          - cargo-size --release | findstr "text __TEXT"
          - cargo-nm --release | findstr "main"
    files:
      recipe:
        - demo-crate/

    requirements:
      run:
        - rust

about:
  homepage: https://github.com/rust-embedded/cargo-binutils
  license: Apache-2.0 OR MIT
  summary: Cargo subcommands to invoke the LLVM tools shipped with the Rust toolchain
  description: |
    Cargo subcommands to invoke the LLVM tools shipped with the Rust toolchain.
