context:
  version: "0.3.6"

package:
  name: cargo-binutils
  version: ${{ version }}

source:
  url: https://github.com/rust-embedded/cargo-binutils/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 431fb12a47fafcb7047d41bdf4a4c9b77bea56856e0ef65c12c40f5fcb15f98f

build:
  script: cargo install --root ${{ PREFIX }} --no-track --locked --path .

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}

tests:
  - package_contents:
      bin:
        - cargo-cov
        - cargo-nm
        - cargo-objcopy
        - cargo-objdump
        - cargo-profdata
        - cargo-readobj
        - cargo-size
        - cargo-strip
        - rust-ar
        - rust-cov
        - rust-ld
        - rust-lld
        - rust-nm
        - rust-objcopy
        - rust-objdump
        - rust-profdata
        - rust-readobj
        - rust-size
        - rust-strip

  - script:
      - if: unix
        then:
          - cd demo-crate
          - cargo size --release | grep -q "text\|__TEXT"
          - cargo nm --release | grep -q "main"
        else:
          - cd demo-crate
          - cargo-size --release | findstr "demo-crate.exe"
          - cargo-nm --release
    files:
      recipe:
        - demo-crate/
    requirements:
      run:
        - rust

about:
  homepage: https://github.com/rust-embedded/cargo-binutils
  license: Apache-2.0 OR MIT
  summary: Cargo subcommands to invoke the LLVM tools shipped with the Rust toolchain
  description: |
    Cargo subcommands to invoke the LLVM tools shipped with the Rust toolchain.
