context:
  version: "0.3.6"

package:
  name: cargo-binutils
  version: ${{ version }}

source:
  url: https://github.com/rust-embedded/cargo-binutils/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 431fb12a47fafcb7047d41bdf4a4c9b77bea56856e0ef65c12c40f5fcb15f98f

build:
  script: cargo install --root $PREFIX --no-track --locked --path .

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}

tests:
  - package_contents:
      files:
        - if: unix
          then:
            - bin/cargo-cov
            - bin/cargo-nm
            - bin/cargo-objcopy
            - bin/cargo-objdump
            - bin/cargo-profdata
            - bin/cargo-readobj
            - bin/cargo-size
            - bin/cargo-strip
            - bin/rust-ar
            - bin/rust-cov
            - bin/rust-ld
            - bin/rust-lld
            - bin/rust-nm
            - bin/rust-objcopy
            - bin/rust-objdump
            - bin/rust-profdata
            - bin/rust-readobj
            - bin/rust-size
            - bin/rust-strip
          else:
            - bin/cargo-cov.exe
            - bin/cargo-nm.exe
            - bin/cargo-objcopy.exe
            - bin/cargo-objdump.exe
            - bin/cargo-profdata.exe
            - bin/cargo-readobj.exe
            - bin/cargo-size.exe
            - bin/cargo-strip.exe
            - bin/rust-ar.exe
            - bin/rust-cov.exe
            - bin/rust-ld.exe
            - bin/rust-lld.exe
            - bin/rust-nm.exe
            - bin/rust-objcopy.exe
            - bin/rust-objdump.exe
            - bin/rust-profdata.exe
            - bin/rust-readobj.exe
            - bin/rust-size.exe
            - bin/rust-strip.exe
  - script:
      - if: unix
        then:
          - cd demo-crate
          - cargo size --release | grep -q "text\|__TEXT"
          - cargo nm --release | grep -q "main"
        else:
          - cd demo-crate
          - cargo-size --release | findstr "text __TEXT"
          - cargo-nm --release | findstr "main"
    files:
      recipe:
        - demo-crate/

    requirements:
      run:
        - rust

about:
  homepage: https://github.com/rust-embedded/cargo-binutils
  license: Apache-2.0 OR MIT
  summary: Cargo subcommands to invoke the LLVM tools shipped with the Rust toolchain
  description: |
    Cargo subcommands to invoke the LLVM tools shipped with the Rust toolchain.
