context:
  version: "0.3.6"

package:
  name: cargo-binutils
  version: ${{ version }}

source:
  url: https://github.com/rust-embedded/cargo-binutils/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 431fb12a47fafcb7047d41bdf4a4c9b77bea56856e0ef65c12c40f5fcb15f98f

build:
  script: cargo install --root $PREFIX --no-track --locked --path .
  skip: win
requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}

tests:
  - script: |
      cd demo-crate

      # Test cargo size command
      cargo size --release | grep -q "text\|__TEXT"

      # Test cargo nm command 
      cargo nm --release | grep -q "main"

    files:
      recipe:
        - demo-crate/

    requirements:
      run:
        - rust

about:
  homepage: https://github.com/rust-embedded/cargo-binutils
  license: Apache-2.0 OR MIT
  summary: Cargo subcommands to invoke the LLVM tools shipped with the Rust toolchain
  description: |
    Cargo subcommands to invoke the LLVM tools shipped with the Rust toolchain.
