[project]
name = "rust-forge"
version = "0.1.0"
description = "Add a short description here"
authors = ["Wolf Vollprecht <w.vollprecht@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64", "win-64", "osx-64"]

[dependencies]
rattler-build = ">=0.31.1,<0.32"

[tasks]
build-all = "rattler-build build -m ./variants.yaml --recipe-dir ./recipes --skip-existing=all -c https://prefix.dev/prefix-package-incubator -c conda-forge"
build = "rattler-build build -m ./variants.yaml -c https://prefix.dev/prefix-package-incubator -c conda-forge --recipe"

[feature.update-versions.dependencies]
python = "3.12.*"
requests = ">=2.32.3,<3"
pyyaml = ">=6.0.2,<7"

[feature.update-versions.tasks]
update-versions = "python .scripts/update-versions.py"

[environments]
update-versions = ["update-versions"]
