context:
  name: serialport-rs-rust-source
  version: "4.6.1"
  sha256: "bf7a47b1d682115b1a93bb722079bb1420041b5dcf149ceb0db8d8e6348c0064"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/serialport/serialport-rs/archive/refs/tags/v${{ version }}.tar.gz
  sha256: ${{ sha256 }}

build:
  number: 0
  script:
    env:
      PKG_SHA256: ${{ sha256 }}
    content:
      - if: linux or osx
        then: "${RECIPE_DIR}/install-rust-source.sh"
        else: "%RECIPE_DIR%\\install_rust_source.bat"

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - setuptools-rust
    - if: linux
      then:
      - libudev

tests:
  - script:
      - if: linux or osx
        then:
          - test -f $PREFIX/src/rust-libraries/${{ name }}-${{ version }}/LICENSE.txt
        else:
          - if not exist %PREFIX%\\src\\rust-libraries\\${{ name }}-${{ version }}\\LICENSE.txt exit 1
  # - downstream: serial-monitor-rust

about:
  homepage: https://github.com/serialport/serialport-rs
  summary: 'A cross-platform serial port library in Rust.'
  description: |
    A cross-platform serial port library in Rust. Provides a blocking I/O
    interface and port enumeration including USB device information.
  license: MPL-2.0
  license_file:
    - LICENSE.txt
    - THIRDPARTY.yml
  repository: https://github.com/serialport/serialport-rs

extra:
  recipe-maintainers:
    - MementoRC
