context:
  name: renode-cli
  version: "1.15.3"
  python_min: "3.6"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/renode/renode/releases/download/v${{ version }}/renode_${{ version }}_source.tar.xz
    sha256: 40c50afe8db86a9c63f4a86b93116a6babd43bf241cfaac47b2c0d2cbc2b15a8
    patches:
      - if: unix
        then:
          - patches/update-IronPython-Renode_NET.csproj.patch
          - patches/update-for-cmake-build.sh.patch
          - patches/update-cores.template_NET.csproj.patch
          - patches/update-IronPython-Unittest_NET.csproj.patch
          - patches/resolve-posix-unix.patch

build:
  number: 0
  noarch: generic

requirements:
  build:
    - dotnet
    - nuget-license
    - renode-cores
    - sed
  host:
    - dotnet
  run:
    - dotnet

tests:
  - package_contents:
      bin:
        - renode
        - renode.cmd
        - renode-test
  - script:
      - renode --help
      - renode-test
    requirements:
      run:
        - robotframework 6.1
        - psutil 5.9.3
        - pyyaml 6.0

about:
  homepage: https://github.com/renode/renode
  summary: "Antmicro's open source simulation and virtual development framework for complex embedded systems"
  description: |
    Renode was created by Antmicro as a virtual development tool for multi-node
    embedded networks (both wired and wireless) and is intended to enable a scalable
    workflow for creating effective, tested and secure IoT systems.

    With Renode, developing, testing, debugging and simulating unmodified software
    for IoT devices is fast, cost-effective and reliable.
  license: MIT
  license_file:
    - LICENSE
    - licensefiles/
  documentation: https://renode.io/
  repository: https://github.com/renode/renode

extra:
  recipe-maintainers:
    - MementoRC
    - danielnachun
