context:
  name: renode-cli
  version: "1.15.3"
  python_min: "3.6"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/renode/renode/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 692604eba16476596ddbc91a4cba1bd5da681dbda076d1980b81f1d333edb7c0
    patches:
      - if: unix
        then:
          - patches/update-IronPython-Renode_NET.csproj.patch
          - patches/update-for-cmake-build.sh.patch
          - patches/resolve-posix-unix.patch
  - git: https://github.com/renode/renode-infrastructure.git
    # rev: 9736cf57e9e9518fe0e53a58cecdb09aee404a4f  # no CMakeLists.txt
    rev: 24c2b35b1b7fb46e47961c08c486fd57c2640b8b
    target_directory: renode-infrastructure
    patches:
      - if: unix
        then:
          - patches/update-IronPython-Unittest_NET.csproj.patch

build:
  number: 0
  noarch: generic

requirements:
  build:
    - dotnet
    - nuget-license
    - git
    - if: unix
      then:
        - ${{ compiler('c') }}
        - ${{ stdlib('c') }}
        - autoconf
        - automake
        - cmake
        - libtool
        - make
        - sed
      else:
        - m2-sed
  host:
    - dotnet
    # - netifaces
    # - psutil
    # - python ${{ python_min }}.*
    # - pyyaml
    # - requests
    # - if: unix
    #   then:
    #     - atk
    #     - cairo
    #     - fontconfig
    #     - gtk3
    #     - glib
    #     - mono
    #     - pango
    #     - pcre
  run:
    - dotnet
    # - netifaces
    # - psutil
    # - python >=${{ python_min }}
    # - pyyaml
    # - requests
    # - robotframework
    # - if: unix
    #   then:
    #     - atk
    #     - cairo
    #     - fontconfig
    #     - gtk3
    #     - glib
    #     - mono
    #     - pango
    #     - pcre

tests:
  - package_contents:
      bin:
        - renode
        - renode.cmd
        - renode-test
  - script:
      - renode --help
      - renode-test

about:
  homepage: https://github.com/renode/renode
  summary: "Antmicro's open source simulation and virtual development framework for complex embedded systems"
  description: |
    Renode was created by Antmicro as a virtual development tool for multi-node
    embedded networks (both wired and wireless) and is intended to enable a scalable
    workflow for creating effective, tested and secure IoT systems.

    With Renode, developing, testing, debugging and simulating unmodified software
    for IoT devices is fast, cost-effective and reliable.
  license: MIT
  license_file:
    - LICENSE
    - licensefiles/
  documentation: https://renode.io/
  repository: https://github.com/renode/renode

extra:
  recipe-maintainers:
    - MementoRC
