context:
  name: egui-phosphor-rust-source
  version: "0.7.3"
  sha256: "076e5598271b9c92565b991cf771b2478740c7a7f66024051e9e74d8d39f7a6f"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/amPerl/egui-phosphor/archive/refs/tags/v${{ version }}.tar.gz
  sha256: ${{ sha256 }}

build:
  number: 0
  script:
    env:
      PKG_SHA256: ${{ sha256 }}
    content:
      - if: linux or osx
        then: "${RECIPE_DIR}/install-rust-source.sh"
        else: "%RECIPE_DIR%\\install_rust_source.bat"

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - setuptools-rust

tests:
  - script:
      - if: linux or osx
        then:
          - test -f $PREFIX/src/rust-libraries/${{ name }}-${{ version }}/LICENSE-MIT
        else:
          - if not exist %PREFIX%\\src\\rust-libraries\\${{ name }}-${{ version }}\\LICENSE-MIT exit 1
  # - downstream: serial-monitor-rust

about:
  homepage: https://github.com/amPerl/egui-phosphor
  summary: 'Phosphor icons for egui.'
  description: |
    Bundles Phosphor icons with boilerplate to use in your egui app.
  license: MIT
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE
  repository: https://github.com/amPerl/egui-phosphor

extra:
  recipe-maintainers:
    - MementoRC
