context:
  name: libjaylink
  version: "0.4.0"
  build_num: 0
  so_version: "0.2.1"
  major_so_version: "0"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://gitlab.zapb.de/libjaylink/libjaylink/-/archive/${{ version }}/libjaylink-${{ version }}.tar.gz
  sha256: 5557d623934a4bbc053c11f9a181375d7abeb76af910696d9e3d9b1de3bf6987

build:
  number: ${{ build_num }}
  skip:
    - win
    - osx

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - libtool
    - ninja
    - pkg-config
  host:
    - libusb
    - meson >=1.1.0

tests:
  - package_contents:
      files:
        - include/libjaylink/libjaylink.h
        - include/libjaylink/version.h
        - lib64/pkgconfig/libjaylink.pc
        - if: linux
          then:
            - lib64/libjaylink.so
            - lib64/libjaylink.so.${{ so_version }}
            - lib64/libjaylink.so.${{ major_so_version }}


about:
  homepage: https://gitlab.zapb.de/libjaylink/libjaylink
  summary: 'libjaylink is a shared library written in C to access SEGGER J-Link.'
  description: |
    libjaylink is a shared library written in C to access SEGGER J-Link and
    compatible devices.
  license: GPL-2.0-or-later
  license_file: COPYING
  repository: https://gitlab.zapb.de/libjaylink/libjaylink

extra:
  recipe-maintainers:
    - MementoRC
  feedstock-name: libjaylink
