context:
  name: serial-monitor-rust
  version: "0.3.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/hacknus/serial-monitor-rust/archive/refs/tags/v${{ version }}.tar.gz
  sha256: ed5382c75d97fd05c8bc95a8b17de12a023fabbe88d7794c05d8ef79ee3a1096
  patches:
    - patches/use-local-rust-sources.patch

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - pkg-config
    # Rust source distributions (pre-compiled/tested on conda-forge)
    - egui-phosphor-rust-source >=0.7.3
    - preferences-rs-rust-source >=2.0.0
    - serialport-rs-rust-source >=4.6.1
  host:
    - keepawake-rs
    - setuptools-rust
    - if: linux
      then:
      - libudev

tests:
  - script:
      - echo "No tests"

about:
  homepage: https://github.com/hacknus/serial-monitor-rust
  summary: 'A cross-plattform serial monitor/plotter written entirely in rust.'
  description: |
    A cross-platform serial monitor and plotter written
    entirely in rust, the GUI is written using egui.
    Inspired by the serial monitor/plotter from the Arduino IDE,
    but both plotting and reading the traffic can be done simultaneously.
  license: GPL-3.0-only
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  repository: https://github.com/hacknus/serial-monitor-rust

extra:
  recipe-maintainers:
    - MementoRC
