context:
  name: renode-cores
  version: "1.15.3"
  python_min: "3.6"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/renode/renode/releases/download/v${{ version }}/renode_${{ version }}_source.tar.xz
    sha256: 40c50afe8db86a9c63f4a86b93116a6babd43bf241cfaac47b2c0d2cbc2b15a8
    patches:
      - patches/update-for-cmake-build.sh.patch

build:
  number: 0

requirements:
  build:
    - cmake
    - if: unix
      then:
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - ${{ stdlib('c') }}
        - make
        - sed
        - tar
      else:
        - ${{ compiler('m2w64_c') }}
        - ${{ compiler('m2w64_cxx') }}
        - ${{ stdlib('m2w64_c') }}
        - m2-base
        - m2-bash
        - m2-sed
        - m2-tar
        - ninja

tests:
  - package_contents:
      files:
        - ${{ "Library/" if not unix }}lib/renode-cores/translate-arm-be.so
        - ${{ "Library/" if not unix }}lib/renode-cores/translate-arm-le.so
        - ${{ "Library/" if not unix }}lib/renode-cores/translate-arm-m-be.so
        - ${{ "Library/" if not unix }}lib/renode-cores/translate-arm-m-le.so
        - ${{ "Library/" if not unix }}lib/renode-cores/translate-arm64-le.so
        - ${{ "Library/" if not unix }}lib/renode-cores/translate-i386-le.so
        - ${{ "Library/" if not unix }}lib/renode-cores/translate-ppc-be.so
        - ${{ "Library/" if not unix }}lib/renode-cores/translate-ppc-le.so
        - ${{ "Library/" if not unix }}lib/renode-cores/translate-riscv-le.so
        - ${{ "Library/" if not unix }}lib/renode-cores/translate-riscv64-le.so
        - ${{ "Library/" if not unix }}lib/renode-cores/translate-sparc-be.so
        - ${{ "Library/" if not unix }}lib/renode-cores/translate-sparc-le.so
        - ${{ "Library/" if not unix }}lib/renode-cores/translate-x86_64-le.so
        - ${{ "Library/" if not unix }}lib/renode-cores/translate-xtensa-le.so
        - if: unix
          then:
            - lib/renode-cores/translate-ppc64-be.so
            - lib/renode-cores/translate-ppc64-le.so
            - etc/conda/activate.d/renode-cores-activate.sh
            - etc/conda/deactivate.d/renode-cores-deactivate.sh
          else:
            - etc/conda/activate.d/renode-cores-activate.bat
            - etc/conda/deactivate.d/renode-cores-deactivate.bat
about:
  homepage: https://github.com/renode/renode
  summary: "Antmicro's open source simulation and virtual development framework for complex embedded systems"
  description: |
    Renode was created by Antmicro as a virtual development tool for multi-node
    embedded networks (both wired and wireless) and is intended to enable a scalable
    workflow for creating effective, tested and secure IoT systems.

    With Renode, developing, testing, debugging and simulating unmodified software
    for IoT devices is fast, cost-effective and reliable.
  license: MIT
  license_file:
    - LICENSE
    - licensefiles/
  documentation: https://renode.io/
  repository: https://github.com/renode/renode

extra:
  recipe-maintainers:
    - MementoRC
    - danielnachun
