context:
  name: keepawake-rs
  version: "0.5.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/segevfiner/keepawake-rs/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 06bfc2ce38a6d06e54fc156bd20afa08ae687b6075d9a4ceb123ec935e8c235a
  patches:
    - if: osx
      then:
        - patches/osx-update-time.patch

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - cmake
  host:
    - setuptools-rust

tests:
  - script:
      - keepawake --help

about:
  homepage: https://github.com/segevfiner/keepawake-rs
  summary: 'Keep your computer awake.'
  description: |
    Keep your computer awake. Like caffeinate,
    systemd-inhibit/gnome-session-inhibit, or PowerToys Awake,
    but cross-platform and written in Rust.
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  documentation: https://crates.io/crates/keepawake
  repository: https://github.com/segevfiner/keepawake-rs

extra:
  recipe-maintainers:
    - MementoRC
